# Generated by Django 5.0.3 on 2024-07-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_video_banner_alter_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_banner',
            field=models.ImageField(upload_to='videos/banner'),
        ),
    ]
